## Training model for CIFAR10

In [ ]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from keras.models import Sequential, load_model
from keras.datasets import cifar10
from keras.utils import np_utils
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D
from keras.callbacks import ModelCheckpoint

In [ ]:
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
x_train = X_train.astype('float32')/255
x_test = X_test.astype('float32')/255
y_train = np_utils.to_categorical(Y_train)
y_test = np_utils.to_categorical(Y_test)

170508288/170498071 [==============================] - 4s 0us/step


In [ ]:
model = Sequential()
model.add(Conv2D(filters=64, kernel_size=3, input_shape=(32, 32, 3), activation='relu', padding='same'))
model.add(Conv2D(filters=64, kernel_size=3, input_shape=(32, 32, 3), activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu', padding='same'))
model.add(MaxPool2D(pool_size=2))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(rate=0.25))
model.add(Dense(10, activation='softmax'))

In [ ]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 64)        1792      
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 64)        36928     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 16, 16, 64)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 16, 16, 128)       73856     
                                                                 
 conv2d_3 (Conv2D)           (None, 16, 16, 128)       147584    
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 8, 8, 128)        0         
 2D)                                                    

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model_checkpoint = ModelCheckpoint('drive/MyDrive/class_Image/HW4/model.hdf5', monitor='val_loss', verbose=1, save_best_only=False)
model.fit(x_train, y_train, epochs=10, batch_size=64, verbose=1, callbacks=[model_checkpoint])

Epoch 1/10
781/782 [============================>.] - ETA: 0s - loss: 0.1292 - accuracy: 0.9576
Epoch 00001: saving model to drive/MyDrive/class_Image/HW4/model.hdf5
782/782 [==============================] - 24s 29ms/step - loss: 0.1292 - accuracy: 0.9576
Epoch 2/10
781/782 [============================>.] - ETA: 0s - loss: 0.1168 - accuracy: 0.9607
Epoch 00002: saving model to drive/MyDrive/class_Image/HW4/model.hdf5
782/782 [==============================] - 22s 29ms/step - loss: 0.1169 - accuracy: 0.9607
Epoch 3/10
781/782 [============================>.] - ETA: 0s - loss: 0.1125 - accuracy: 0.9620
Epoch 00003: saving model to drive/MyDrive/class_Image/HW4/model.hdf5
782/782 [==============================] - 22s 29ms/step - loss: 0.1126 - accuracy: 0.9620
Epoch 4/10
781/782 [============================>.] - ETA: 0s - loss: 0.1170 - accuracy: 0.9609
Epoch 00004: saving model to drive/MyDrive/class_Image/HW4/model.hdf5
782/782 [==============================] - 22s 29ms/step - loss

In [ ]:
loss, accuracy = model.evaluate(x_test, y_test)
print('Test:')
print('Loss:', loss)
print('Accuracy:', accuracy)

313/313 [==============================] - 3s 9ms/step - loss: 1.3406 - accuracy: 0.7778
Test:
Loss: 1.340636134147644
Accuracy: 0.7778000235557556


## Get three kernels from model after training

In [1]:
from keras.models import load_model

model = load_model('drive/MyDrive/class_Image/HW4/model.hdf5')

#### layer 0

In [ ]:
layer_num = 0

In [ ]:
all_kernels, biases = model.layers[layer_num].get_weights()
print(all_kernels.shape)
print(biases.shape)

(3, 3, 3, 64)
(64,)


In [ ]:
import random

chosen_kernels = []

for i in range(20):
  chosen_kernels.append( all_kernels[:,:,:,i] )

for i in range(len(chosen_kernels)):
  print(i)
  print(chosen_kernels[i])
  print()

[[[ 0.00497072 -0.15258037 -0.22455686]
  [-0.07347262 -0.16462183 -0.17328459]
  [-0.0617498  -0.10344191 -0.11840715]]

 [[ 0.09040552  0.1244745   0.0197518 ]
  [ 0.08187189  0.12061322 -0.03591486]
  [-0.04829563  0.06485029 -0.10978864]]

 [[-0.2929674  -0.31493354 -0.10019614]
  [-0.3002111  -0.23391756 -0.30247512]
  [-0.22419527 -0.36716744 -0.29111245]]]

[[[ 0.11288493  0.06821454 -0.11600643]
  [ 0.10795915  0.05834523 -0.14704402]
  [-0.06678109 -0.08439957  0.02054661]]

 [[ 0.14067578  0.11870353 -0.07217357]
  [ 0.11805544  0.09222941 -0.17893292]
  [-0.27118772 -0.17238733 -0.03275371]]

 [[ 0.10878824  0.07363927 -0.13982593]
  [ 0.05689394 -0.09578826 -0.10648343]
  [-0.17133461 -0.23263107  0.02885778]]]

[[[-0.20507862 -0.01460768 -0.06313529]
  [-0.10182933 -0.10870101 -0.14355801]
  [-0.1580708  -0.09349517  0.01773739]]

 [[-0.05939748  0.04606272 -0.17162701]
  [-0.14962664 -0.10699771 -0.24714138]
  [ 0.02964118  0.02605474 -0.02934928]]

 [[ 0.07948337  0.0942

In [ ]:
import cv2
import numpy as np
from pathlib import Path

COLOR = 3
KERNEL_SIZE = 3

# read image
origin_img = cv2.imread( 'drive/MyDrive/class_Image/HW4/images/cupcake.jpg' )

# convolution
height = origin_img.shape[0]
width = origin_img.shape[1]

cov_imgs = np.zeros( [ len(chosen_kernels), height+4, width+4, 3 ]) # add padding

cov_range = int((KERNEL_SIZE-1)/2)
for i in range(len(chosen_kernels)):
  kernel = chosen_kernels[i]
  for y in range(cov_range, height-cov_range):
      for x in range(cov_range, width-cov_range):
          part_img = origin_img[ y-1:y+2, x-1:x+2, : ]
          for color in range(0, COLOR):
              value = abs(np.sum(part_img[:,:,color] * kernel[:,:,color]))
              cov_imgs[i,y,x,color] = value
  print('covolution : kernel', i, 'done.')

cov_imgs = cov_imgs[:, KERNEL_SIZE-1:-(KERNEL_SIZE-1), KERNEL_SIZE-1:-(KERNEL_SIZE-1),:] # remove padding

# write convolution images
output_dir = Path.cwd() / 'drive/MyDrive/class_Image/HW4/images/output_img'
Path.mkdir( output_dir, exist_ok=True)

for i in range(cov_imgs.shape[0]):
  cv2.imwrite( str(output_dir)+'/kernel_'+str(layer_num)+'_'+str(i)+'.jpg', cov_imgs[i] )

print('save images done.')

covolution : kernel 0 done.
covolution : kernel 1 done.
covolution : kernel 2 done.
covolution : kernel 3 done.
covolution : kernel 4 done.
covolution : kernel 5 done.
covolution : kernel 6 done.
covolution : kernel 7 done.
covolution : kernel 8 done.
covolution : kernel 9 done.
covolution : kernel 10 done.
covolution : kernel 11 done.
covolution : kernel 12 done.
covolution : kernel 13 done.
covolution : kernel 14 done.
covolution : kernel 15 done.
covolution : kernel 16 done.
covolution : kernel 17 done.
covolution : kernel 18 done.
covolution : kernel 19 done.
save images done.


#### layer 0 -grey

In [6]:
layer_num = 0

In [7]:
all_kernels, biases = model.layers[layer_num].get_weights()
print(all_kernels.shape)
print(biases.shape)

(3, 3, 3, 64)
(64,)


In [8]:
import random

chosen_kernels = []

for i in range(10,20):
  chosen_kernels.append( all_kernels[:,:,:,i] )

for i in range(len(chosen_kernels)):
  print(i)
  print(chosen_kernels[i])
  print()

0
[[[-0.10847659 -0.07223421 -0.04077852]
  [-0.05441006  0.0128111  -0.03104441]
  [-0.03458859 -0.05456475  0.02603482]]

 [[ 0.01130721 -0.07016428  0.02272065]
  [ 0.01883971 -0.02989899 -0.01811647]
  [-0.08763019  0.03085222  0.01218058]]

 [[-0.07497621 -0.10924009 -0.05030665]
  [-0.02776211  0.00076088  0.02215889]
  [-0.10188843  0.03484473 -0.0894475 ]]]

1
[[[-0.01931943 -0.04688984 -0.0637237 ]
  [-0.03205682 -0.07354354 -0.08076991]
  [-0.06495786  0.03823904 -0.06192773]]

 [[-0.04728746 -0.02411581  0.04780945]
  [ 0.00409489 -0.17048438  0.02278068]
  [ 0.02378267 -0.04610307 -0.1119182 ]]

 [[-0.10879003  0.03451513 -0.07002791]
  [ 0.00432815  0.00261283 -0.07033987]
  [ 0.02832262 -0.13432173 -0.1039389 ]]]

2
[[[-0.09396089 -0.04256    -0.02652537]
  [ 0.07365009  0.03540148  0.12019425]
  [-0.00322518 -0.15626624 -0.20164126]]

 [[-0.1277812  -0.11958694  0.08720494]
  [ 0.30158237  0.18601039  0.38110244]
  [ 0.09091933 -0.16940206  0.07611309]]

 [[ 0.04854676  

In [9]:
import cv2
import numpy as np
from pathlib import Path

COLOR = 3
KERNEL_SIZE = 3

# read image
origin_img = cv2.imread( 'drive/MyDrive/class_Image/HW4/images/cupcake.jpg' )

# convolution
height = origin_img.shape[0]
width = origin_img.shape[1]

cov_imgs = np.zeros( [ len(chosen_kernels), height+4, width+4, 3 ]) # add padding

cov_range = int((KERNEL_SIZE-1)/2)
for i in range(len(chosen_kernels)):
  kernel = chosen_kernels[i]
  for y in range(cov_range, height-cov_range):
      for x in range(cov_range, width-cov_range):
          part_img = origin_img[ y-1:y+2, x-1:x+2, : ]
          for color in range(0, COLOR):
              value = abs(np.sum(part_img[:,:,color] * kernel[:,:,color]))
              cov_imgs[i,y,x,color] = value
  print('covolution : kernel', i, 'done.')

cov_imgs = cov_imgs[:, KERNEL_SIZE-1:-(KERNEL_SIZE-1), KERNEL_SIZE-1:-(KERNEL_SIZE-1),:] # remove padding

# write convolution images
output_dir = Path.cwd() / 'drive/MyDrive/class_Image/HW4/images/output_img'
Path.mkdir( output_dir, exist_ok=True)

for i in range(cov_imgs.shape[0]):
  cv2.imwrite( str(output_dir)+'/kernel_'+str(layer_num)+'_grey0_'+str(i)+'.jpg', cov_imgs[i,:,:,0] )
  cv2.imwrite( str(output_dir)+'/kernel_'+str(layer_num)+'_grey1_'+str(i)+'.jpg', cov_imgs[i,:,:,1] )
  cv2.imwrite( str(output_dir)+'/kernel_'+str(layer_num)+'_grey2_'+str(i)+'.jpg', cov_imgs[i,:,:,2] )

print('save images done.')

covolution : kernel 0 done.
covolution : kernel 1 done.
covolution : kernel 2 done.
covolution : kernel 3 done.
covolution : kernel 4 done.
covolution : kernel 5 done.
covolution : kernel 6 done.
covolution : kernel 7 done.
covolution : kernel 8 done.
covolution : kernel 9 done.
save images done.
